# Generated by Django 4.2 on 2023-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='charities/images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_charities',
            field=models.ManyToManyField(blank=True, to='charities.charities'),
        ),
    ]
