# Generated by Django 4.2 on 2023-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_charities_image_user_liked_charities'),
    ]

    operations = [
        migrations.AddField(
            model_name='charities',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
