# Generated by Django 4.2 on 2023-04-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_charities_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charities',
            name='image',
        ),
        migrations.AddField(
            model_name='charities',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
