# Generated by Django 4.2 on 2023-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_remove_charities_image_charities_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='charities',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
